package:
  name: taxcalc
  version: 0.0.0

build:
  entry_points:
    - tc = taxcalc.cli.tc:cli_tc_main

requirements:
  build:
    - "python>=3.6"
    - "numpy>=1.13"
    - "pandas>=0.23"
    - "bokeh>=0.13"
    - numba

  run:
    - "python>=3.6"
    - "numpy>=1.13"
    - "pandas>=0.23"
    - "bokeh>=0.13"
    - numba

test:
  commands:
    - which tc  # [unix]
    - where tc  # [win]
    - tc --help

about:
  home: https://github.com/open-source-economics/Tax-Calculator
