name: Get new citations bibtex file

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Action for curl
        uses: wei/curl@v1.1.1
        with:
          args: curl -H 'Zotero-API-Version: 2' -H 'Zotero-API-Key: MiQBsz0ilWhpsmQJyqeO2TzU' 'https://api.zotero.org/groups/2524233/items?format=bibtex' --output citations.bib
          
      - name: new commit
        shell: bash -l {0}
        run: |
          export DATE=`date +%Y-%m-%d`
          export BRANCH_NAME=citations-$DATE
          git checkout -b $BRANCH_NAME
          git status
          git add -A
          git commit -m "Update citations for date $DATE"
          git push --set-upstream origin catalog-$DATE
          git checkout master
          git pull --no-edit origin $BRANCH_NAME
          git push origin master
          git branch -D $BRANCH_NAME
          git push origin --delete $BRANCH_NAME
